[profile.default]
evm_version = "cancun"
src = "src"
out = "out"
script = "script"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "out-optimized" }, { access = "read-write", path = "gas_calculations" }]
allow_paths = ["*", "/"]
ignored_warnings_from = ["node_modules"]
solc = "0.8.26"
optimizer_runs = 1000000
auto_detect_remappings = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}" 

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
